INSERT INTO user VALUES ('1', 'ANDAMAN PRAGATI COCONUT PRODUCER COMPANY LIMITED', 'Andaman and Nicobar Islands', 'subbiahandco@gmail.com');
INSERT INTO user VALUES ('2', 'DWEEPAM AGRI PRODUCER COMPANY LIMITED', 'Andaman and Nicobar Islands', 'primekoss@hotmail.com');
INSERT INTO user VALUES ('3', 'ADHITHI MILK AND AGRI PRODUCER COMPANY LIMITED', 'Andaman and Nicobar Islands', 'subbiahandco@gmail.com');
INSERT INTO user VALUES ('4', 'ANDAMAN AND NICOBAR ISLANDS FOREST AND PLANTATION DEVELOPMENT CORPORATION LIMITED..', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('5', 'ANDAMAN WOOD WORKS PRIVATE LIMITED.', 'Andaman and Nicobar Islands', 'vaksusi@gmail.com');
INSERT INTO user VALUES ('6', 'ANDAMAN WOOD PRODUCES (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'nirmalkaushik@hotmail.com');
INSERT INTO user VALUES ('7', 'BAY ISLAND FISHERIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('8', 'MADURAI MEENAKSHI FISHING COMPANY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('9', 'GATEWAY FISHING & LOGISTICS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('13', 'ANDAMAN FISHERIES LIMITED', 'Andaman and Nicobar Islands', 'aniidco@gmail.com');
INSERT INTO user VALUES ('15', 'SOLOM TRADING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'subashinirubin@gmail.com');
INSERT INTO user VALUES ('16', 'AQUATROPICS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'varmaspace@gmail.com');
INSERT INTO user VALUES ('17', 'ANDAMAN STONE PRODUCTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('18', 'IYYAN BLUE METALS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('19', 'ANDAMAN PAINTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'applindia@yahoo.com');
INSERT INTO user VALUES ('20', 'DOOJAIN TRADELINES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'doojainconfac@gmail.com');
INSERT INTO user VALUES ('21', 'U AND I RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('22', 'SEA GRASS RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'gulmuhar21031986@gmail.com');
INSERT INTO user VALUES ('23', 'ANDAMAN MOUNT HARRIAT RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'SKSSTALIN@REDIFFMAIL.COM');
INSERT INTO user VALUES ('25', 'HOTEL ANDAMAN SEA RESORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'akayes123@gmail.com');
INSERT INTO user VALUES ('27', 'BLUE SEA HOTELS(ANDAMANS) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roybagchi@gmail.com');
INSERT INTO user VALUES ('28', 'ANDAMAN RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('29', 'HOTEL DHANALAKSHMI PRIVATE LIMITED.', 'Andaman and Nicobar Islands', 'roybagchi@gmail.com');
INSERT INTO user VALUES ('30', 'HOTEL ABHISHEKH (ANDAMANS) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roybagchi@gmail.com');
INSERT INTO user VALUES ('31', 'ISLET FOOD PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'nirmalkaushik@hotmail.com');
INSERT INTO user VALUES ('32', 'HOTEL APARUPA (ANDAMANS) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'hotelaparupa@yahoo.com');
INSERT INTO user VALUES ('33', 'SUN SEA RESORT PRIVATE LIMITED.', 'Andaman and Nicobar Islands', 'roybagchi@gmail.com');
INSERT INTO user VALUES ('35', 'CORAL SEA RESORT (ANDAMAN) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('36', 'HOTEL SARVOTTAM (ANDAMAN) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('37', 'BLUE PLANET HOTELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('38', 'ABERDEEN HOTELS & ESTATES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roybagchi@gmail.com');
INSERT INTO user VALUES ('39', 'MUNJOH RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('40', 'ANDAMAN DOWN UNDER RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('41', 'PRINCE HOLIDAY INN PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sagar.khurana@hotmail.com');
INSERT INTO user VALUES ('42', 'BAY WATCH HOTEL & RESORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'dabayinnandaman@rediffmail.com');
INSERT INTO user VALUES ('43', 'BLUE GREEN BEACH RESORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('44', 'BLUE GREEN VENTURES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'chendooran.pathmanathan@gmail.com');
INSERT INTO user VALUES ('45', 'FALCON RESORT (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('46', 'JADWET RESORTS AND LEISURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('47', 'MANSHA HOSPITALITY AND SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('48', 'AKABEA RESORTS AND LEISURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'javed.khan@msn.com');
INSERT INTO user VALUES ('49', 'WHITE CORAL BEACH RESORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('50', 'HOLIDAY INN BEACH RESORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'holidayinn_havelock@yahoo.in');
INSERT INTO user VALUES ('51', 'HOTEL BLUE WAVES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('52', 'ROYAL RESORTS & LEISURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('53', 'WOODQUARTER RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'susheeldixit63@gmail.com');
INSERT INTO user VALUES ('54', 'SLR HOSPITALITY (ANDAMAN) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'andamanleisure@gmail.com');
INSERT INTO user VALUES ('55', 'EMERALD GECKO(ANDAMANS) RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('56', 'JOYE GRAND HOTEL PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('58', 'JADWET HOTELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('59', 'SUDHARSHAN ECO FRIENDLY RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('60', 'HAVELOCK COCONUT LEISURE RESORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ajitroykr@gmail.com');
INSERT INTO user VALUES ('61', 'LUSH GREEN ISLAND RESORTS AND TRADE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'pkentp@yahoo.co.in');
INSERT INTO user VALUES ('62', 'SEA STAR BEACH RESORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('63', 'COCONHUTS (ANDAMAN) BEACH RESORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('64', 'ANDAMAN RAMTULSI PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'TAMARAISELVI9@GMAIL.COM');
INSERT INTO user VALUES ('65', 'HAYWIZZ ELITE HAVELOCK ISLAND RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'haywizzelite@gmail.com');
INSERT INTO user VALUES ('66', 'MANIKA VINAYAGAR HOTEL PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sentnin14680@gmail.com');
INSERT INTO user VALUES ('67', 'SRI PONNU SWAMY ENTERPRISES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'anburamu1988@gmail.com');
INSERT INTO user VALUES ('68', 'ATOMIUM HOTELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'nirapada321@gmail.com');
INSERT INTO user VALUES ('69', 'ANDAMANS PACKERS AND MOVERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('71', 'AMMAN POULTRY AND FEEDS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'murugang1978@gmail.com');
INSERT INTO user VALUES ('72', 'ISLAND ORGANIC PRODUCER COMPANY LIMITED', 'Andaman and Nicobar Islands', 'ANDAMANCPC@GMAIL.COM');
INSERT INTO user VALUES ('73', 'MAYABUNDER AGRICULTURAL PRODUCER COMPANY LIMITED', 'Andaman and Nicobar Islands', 'JAYANTANAGBOD@GMAIL.COM');
INSERT INTO user VALUES ('77', 'APIARY PRODUCER COMPANY LIMITED', 'Andaman and Nicobar Islands', 'ANDAMANCPC@GMAIL.COM');
INSERT INTO user VALUES ('78', 'OCEANIC AGRO TECH PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('79', 'VINOTH FEEDS AND POULTRY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('80', 'ILANCE DEVELOPERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'd.umailme@rediffrnail.com');
INSERT INTO user VALUES ('81', 'GENNEXT MOTORS(ANDAMANS) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sagar.khurana@hotmail.com');
INSERT INTO user VALUES ('82', 'ANDAMAN MOTORS PRIVATE LIMITED.', 'Andaman and Nicobar Islands', 'sajid@andamanmotors.com');
INSERT INTO user VALUES ('83', 'DHEERAJ MOTOR PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'lawflo@gmail.com');
INSERT INTO user VALUES ('84', 'PREETA CARS (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'preetacarsindiapltd@gmail.com');
INSERT INTO user VALUES ('85', 'COASTAL SEAWAYS (ISLAND) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'coastalcruise@ymail.com');
INSERT INTO user VALUES ('87', 'MOHAN AUTOMOTIVES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'efile.casatya@gmail.com');
INSERT INTO user VALUES ('88', 'GOVINDAMMA TRADING CO PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'gdmyamaha@yahoo.co.in');
INSERT INTO user VALUES ('89', 'ANDAMAN & NICOBAR TECHNOLOGY LAB PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'nadeemixz@gmail.com');
INSERT INTO user VALUES ('90', 'AHAAN AUTOMOBILES (ANDAMAN) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sagar.khurana@hotmail.com');
INSERT INTO user VALUES ('91', 'GENNEXT HEAVY EQUIPMENTS (ANDAMANS) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sagar.khurana@hotmail.com');
INSERT INTO user VALUES ('92', 'NEXT GEN AUTOMOBILES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'vinodca@hotmail.com');
INSERT INTO user VALUES ('93', 'CHANAKYA CONSULTANCY SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ca.patel@vlp.co.in');
INSERT INTO user VALUES ('94', 'RATHINA VINAYAKAR METALS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'NANDUNANDY2012@GMAIL.COM');
INSERT INTO user VALUES ('95', 'ARYAN AQUA (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc.casatya@gmail.com');
INSERT INTO user VALUES ('96', 'ICY SPICY ICE CREAM PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'rajeshbagla@gmail.com');
INSERT INTO user VALUES ('97', 'JEHOVAN MARINE EXPORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'jsmarineseafoods@gmail.com');
INSERT INTO user VALUES ('98', 'ICY SPICY FOODS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'legal@icyspicy.in');
INSERT INTO user VALUES ('99', 'BLAIR FOOD PRODUCTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'UMANG@ICYSPICY.IN');
INSERT INTO user VALUES ('100', 'CALCUTTA FOOD AND BOTTLING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('101', 'ECOGEN CRYSTALLINE WATER PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('102', 'A & N INDIA MARKETING SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mca.samrat@rediffmail.com');
INSERT INTO user VALUES ('103', 'KARAN TRADING (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'pearlanil@rediffmail.com');
INSERT INTO user VALUES ('104', 'VENKATESHWARA HARDWARE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('105', 'AKR FRESH VEG & FROZEN FOODS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'abdulkani6441@gmail.com');
INSERT INTO user VALUES ('106', 'MOUNTAIN EDGE TOURS AND HOLIDAYS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mountainedgepb@gmail.com');
INSERT INTO user VALUES ('107', 'AGENCY HOUSE (A&N ISLANDS) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ravichandransca.efile@gmail.com');
INSERT INTO user VALUES ('108', 'DE MEADOWS (ANDAMANS) RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roybagchi@gmail.com');
INSERT INTO user VALUES ('109', 'NELLAIH FEEDS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'RAVICHANDRANSCA@YAHOO.COM');
INSERT INTO user VALUES ('110', 'ABLE TOURISM (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'nadeemixz@gmail.com');
INSERT INTO user VALUES ('111', 'PETROFICIENT ENGINEERING SOLUTIONS LIMITED', 'Andaman and Nicobar Islands', 'aktport@gmail.com');
INSERT INTO user VALUES ('112', 'NANDA AGENCY HOUSE SHIPPING SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'agencypbl@gmail.com');
INSERT INTO user VALUES ('113', 'OCEAN REEFS (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 's1982m1983@gmail.com');
INSERT INTO user VALUES ('114', 'CHAKRABORTY MULTI-SPECIALITY HOSPITAL PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('115', 'ROYAL PETROLEUM (ANDAMAN) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ZUBI.BEGUM@GMAIL.COM');
INSERT INTO user VALUES ('116', 'ANDAMAN SAFARIS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'AJAYKANDAMAN@GMAIL.COM');
INSERT INTO user VALUES ('117', 'GO COOL NEXT GEN PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('118', 'FEEL GOOD VENTURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc.cassatya@gmail.com');
INSERT INTO user VALUES ('119', 'AKSPEARLS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'AJAISONKAR@GMAIL.COM');
INSERT INTO user VALUES ('120', 'SIVASELVAM STORES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'caravichandrans@gmail.com');
INSERT INTO user VALUES ('121', 'K P TRADING & COMPANY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc.casatya@gmail.com');
INSERT INTO user VALUES ('123', 'SEA BAY TRADELINKS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'balaji_kanneganti@rediffmail.com');
INSERT INTO user VALUES ('124', 'JADWET TRADING COMPANY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mhjadwet@hotmail.com');
INSERT INTO user VALUES ('125', 'R.AKOOJI JADWET AND COMPANY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('126', 'SILVER SKY ENTERPRISES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('127', 'PRINCE STORES (TRADING) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sagar.khurana@hotmail.com');
INSERT INTO user VALUES ('128', 'SAKTHI HARDWARES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('129', 'SELVAM STORE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'selvam8167@gmail.com');
INSERT INTO user VALUES ('130', 'ISLANDERS MARGIN FREE CANTEEN PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'imfcandaman@gmail.com');
INSERT INTO user VALUES ('131', 'LONSIM HARDWARES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sblmakeinindia@gmail.com');
INSERT INTO user VALUES ('132', 'KANCHIPURAM SABTHAGIRI SILKS SAREES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sabthgirisilks@gmail.com');
INSERT INTO user VALUES ('133', 'VCARE DRUGS AND PHARMACEUTICALS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('134', 'DIGITAL ARTS TECHNOLOGIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('135', 'ROYAL DIGITAL PRINTER PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('136', 'SRI MAKAABHA PAPER PRODUCTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'karthik.katty9@gmail.com');
INSERT INTO user VALUES ('139', 'GATEWAY PRODUCTIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('140', 'KRG PUBLICATIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'krgprivatelimited@gmail.com');
INSERT INTO user VALUES ('141', 'ANI NEWS AND ADVERTISING AGENCY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'JOHN09434288588@GMAIL.COM');
INSERT INTO user VALUES ('146', 'ANDAMAN & NICOBAR FINANCE & INVESTMENT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'bikashdas17021973@gmail.com');
INSERT INTO user VALUES ('149', 'L M STAR AUTOTRADE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'murugang1978@gmail.com');
INSERT INTO user VALUES ('150', 'ANDAMAN PROPERTIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mhjadwet@hotmail.com');
INSERT INTO user VALUES ('151', 'MOHAN SINGH INFRASTRUCTURE(INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('152', 'AROCKIA MADHA PROPERTIES & CONSTRUCTIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('153', 'FLYWHEEL REALTY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'NVSABITH@GMAIL.COM');
INSERT INTO user VALUES ('154', 'KEC PROJECTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'chadhakailash25@gmail.com');
INSERT INTO user VALUES ('155', 'ASANS PROJECTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc.casatya@gmail.com');
INSERT INTO user VALUES ('156', 'ISLAND GATEWAY PROPERTY DEVELOPERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('157', 'SWAMY VINAYAGAR REAL ESTATE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'GDURAISWAMY.DSC@GMAIL.COM');
INSERT INTO user VALUES ('158', 'LUCKY HOME REAL ESTATE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ajay500capitaltandt@gmail.com');
INSERT INTO user VALUES ('159', 'HANIF INFRASTRUCTURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'hanif.hanif755@gmail.com');
INSERT INTO user VALUES ('160', 'TOTTOCRAFT TECHNOLOGIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roy.swapnesh@gmail.com');
INSERT INTO user VALUES ('161', 'GKR TECHSOFT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'gkrtechnology@gmail.com');
INSERT INTO user VALUES ('162', 'DIVYANGA TECHNOLOGY SOLUTIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('163', 'SUNNY POWER TECH PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'satya_ani@sify.com');
INSERT INTO user VALUES ('164', 'ANDAMAN WATERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'captvenkat@gmail.com');
INSERT INTO user VALUES ('165', 'RCS INFRASTRUCTURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('166', 'MALIK INFRASTRUCTURE (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('167', 'BHARAT MULTITECH INDUSTRIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('168', 'AYUSH JOTI BUILDERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('169', 'MADURAI MEENAKSHI CONSTRUCTION (INDIA)PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'MAILVLP@AOL.COM');
INSERT INTO user VALUES ('170', 'ARASI PROJECTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'efile.casatya@gmail.com');
INSERT INTO user VALUES ('171', 'SAKTHI BUILDERS (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('172', 'S K S & DEVELOPERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc.casatya@gmail.com');
INSERT INTO user VALUES ('173', 'PRASHANTH ERECTOR AND BUILDERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roybagchi@gmail.com');
INSERT INTO user VALUES ('174', 'LEMON HOUSING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('175', 'ARQ PROPERTIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('176', 'CSE CONSTRUCTION (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'group_engineers@rediffmail.com');
INSERT INTO user VALUES ('177', 'ANDAMAN & NICOBAR MICRO FINANCE CONSULTANCY LIMITED', 'Andaman and Nicobar Islands', 'bikashdas17021973@gmail.com');
INSERT INTO user VALUES ('178', 'OUR CLCTODAY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'razakhan336@gmail.com');
INSERT INTO user VALUES ('179', 'SKIER PROPERTIES DEVELOPER PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('180', 'LOKENATH INFRA DEVELOPER PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc.casatya@gmail.com');
INSERT INTO user VALUES ('183', 'S.H. REALTORS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'cababubadat@gmail.com');
INSERT INTO user VALUES ('184', 'LOKENATH REAL ESTATE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('185', 'A G P CONSTRUCTIONS COMPANY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('186', 'KAMPS PROJECTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'kampspbl@yahoo.com');
INSERT INTO user VALUES ('187', 'ANDAMAN NIRMAN PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sriomtraders@rediffmail.com');
INSERT INTO user VALUES ('188', 'HITECH CIVIL ENGINEERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ravichandransca@yahoo.com');
INSERT INTO user VALUES ('189', 'ISLAND REALCON INDIA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'islandrealcon@gmail.com');
INSERT INTO user VALUES ('190', 'ARUL EARTH MOVERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('191', 'SALCON INFRA ENGINEERING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'saluja_sharnjit@rediffmail.com');
INSERT INTO user VALUES ('192', 'JAYA REALTORS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('193', 'Z KING GLOBAL REAL ESTATE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roybagchi@gmail.com');
INSERT INTO user VALUES ('194', 'R G T CITY REAL ESTATE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('195', 'SHIKSHA CONTRACTORS AND TRADERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'MAIL2DHARVINDER@GMAIL.COM');
INSERT INTO user VALUES ('196', 'VISTARAN DEVELOPERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'VISTARANDEVELOPERS@GMAIL.COM');
INSERT INTO user VALUES ('198', 'EPAY COMPUTER SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@vlp.co.in');
INSERT INTO user VALUES ('199', 'M N V INFRASTRUCTURE (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'CA.PATEL@VLP.CO.IN');
INSERT INTO user VALUES ('200', 'MANICKAM PROJECTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('201', 'S K SHAKTI BUILDERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'MAILVLP@AOL.COM');
INSERT INTO user VALUES ('202', 'GCVD INFRATECH PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'efile.casatya@gmail.com');
INSERT INTO user VALUES ('203', 'AL VIJAY INFRASTRUCTURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('204', 'R.M SATTAIAPPAN CONSTRUCTION PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('205', 'M SUBRAMANIAM ENGINEERING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc.casatya@gmail.com');
INSERT INTO user VALUES ('206', 'P SURYA RAO CONSTRUCTION (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'CA.PATEL@VLP.CO.IN');
INSERT INTO user VALUES ('207', 'ANID PROJECTS LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('208', 'LALL INFRASTRUCTURES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('209', 'C M ROY CONSTRUCTION PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'cmroycontractor@yahoo.com');
INSERT INTO user VALUES ('210', 'MANICKAM CONSTRUCTIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('211', 'RAVI REALCON PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ravirealconpltd@gmail.com');
INSERT INTO user VALUES ('212', 'ISLANDER HOUSING PROJECT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'imfchousing@gmail.com');
INSERT INTO user VALUES ('213', 'BISWORTH CONSTRUCTIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'abhishekbiswas454@gmail.com');
INSERT INTO user VALUES ('214', 'ANIIDA DEVELOPERS AND PROMOTERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ANNIIDAPVTLTD@GMAIL.COM');
INSERT INTO user VALUES ('215', 'CUSP DEVELOPERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roseminegroup@gmail.com');
INSERT INTO user VALUES ('216', 'VDR BLUE METAL PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'dscindia3@gmail.com');
INSERT INTO user VALUES ('217', 'AKABEA INFRASTRUCTURES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'javed@akabea.com');
INSERT INTO user VALUES ('218', 'ANDAMAN BUILDSMORE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'contact@tttrading.in');
INSERT INTO user VALUES ('219', 'SWATHI ANDAMAN INFRASTRUCTURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'vivekmanian2015@gmail.com');
INSERT INTO user VALUES ('220', 'HOTEL BLUE LAGOON(ANDAMAN) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('221', 'S L PROJECTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('222', 'GST CONSTRUCTION PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('223', 'SRILEKSHMIVIHAR PROPERTIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('224', 'K C M BUILDERS AND CONSTRUCTIONS (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('225', 'S P SHUKLA BUILDERS AND CONTRACTORS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('226', 'MM KAILASH CONSTRUCTION PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'chadhakailash25@gmail.com');
INSERT INTO user VALUES ('227', 'P.G EAPPEN CONSTRUCTION PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'pgeappen08@gmail.com');
INSERT INTO user VALUES ('228', 'MSM TECHNO PROJECTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ravichandransca.efile@gmail.com');
INSERT INTO user VALUES ('229', 'TEJA PROJECTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('230', 'A T SHANMUGAM CONSTRUCTION PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'athi2683@gmail.com');
INSERT INTO user VALUES ('231', 'M.R.L BUILDERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'krishna.mrl@hotmail.com');
INSERT INTO user VALUES ('232', 'PARIVAAR S. R. PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sandipbiswas20082@gmail.com');
INSERT INTO user VALUES ('233', 'ARQ ADVERTISING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'bharatvermas@yahoo.com');
INSERT INTO user VALUES ('234', 'NEXT GENERATION RETAIL PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roybagchi@gmail.com');
INSERT INTO user VALUES ('236', 'IMPERIAL AGENCIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'akayes123@gmail.com');
INSERT INTO user VALUES ('238', 'EMERALD MARKETING SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'fyjgroup@hotmail.com');
INSERT INTO user VALUES ('239', 'E CAVE SHOPEE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'cavineetdixit@gmail.com');
INSERT INTO user VALUES ('240', 'FY TRADING COMPANY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'jadwet@hotmail.com');
INSERT INTO user VALUES ('241', 'MEGAPODE TRADING COMPANY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'softech_computers@rediffmail.com');
INSERT INTO user VALUES ('242', 'G.S.K.P STORES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('243', 'S.L ENTERPRISES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('246', 'ANDAMAN COMPUTERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('249', 'RAHMAT TRADING COMPANY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.COIN');
INSERT INTO user VALUES ('250', 'K.DORAISWAMY TRADING CO.PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'pblktco@bsnl.in');
INSERT INTO user VALUES ('251', 'SRI KRISHNAVENI TRADING COMPANY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'pblktco@sancharnet.in');
INSERT INTO user VALUES ('252', 'VISION ADVERTISING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'efile.casatya@gmail.com');
INSERT INTO user VALUES ('253', 'ZAM SECURITIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ihbadat@gmail.com');
INSERT INTO user VALUES ('254', 'ANDAMAN CLUB PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'arorapb@gmail.com');
INSERT INTO user VALUES ('255', 'GENEX RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'skynetfm@live.com');
INSERT INTO user VALUES ('256', 'TALK AND TRIP MARKETING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'vinaykhannadiamond@gmail.com');
INSERT INTO user VALUES ('259', 'ANDAMAN AND NICOBAR ISLANDS INTEGRATED DEVELOPMENT CORPORATION LIMITED.', 'Andaman and Nicobar Islands', 'aniidco@gmail.com');
INSERT INTO user VALUES ('260', 'KRISHPRATAP PLACEMENT SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'kuldeep.portblair@rediffmail.com');
INSERT INTO user VALUES ('261', 'VANGUARD SHIPPING SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ganesh1278@gamil.com');
INSERT INTO user VALUES ('262', 'OCEAN TRIBE SCUBA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ocean.tribe.scuba@gmail.com');
INSERT INTO user VALUES ('263', 'BEST FOR YOU GOOD APPLIANCES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mca@bmcgroup.in');
INSERT INTO user VALUES ('264', 'ANDAMAN INNOVATIVE SYSTEMS & LOGISTICS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'isl_pb@rediffmail.com');
INSERT INTO user VALUES ('265', 'DAAM UDYOG INDIA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'saidheerajsingh@gmail.com');
INSERT INTO user VALUES ('266', 'MU STUDIOS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'nmkathiravan@gmail.com');
INSERT INTO user VALUES ('267', 'OASIS PLAZA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('268', 'MARUDHU PANDIYAN SECURITY & FACILITY MANAGEMENT SERVICE PRIVATE LIMITED (OPC)', 'Andaman and Nicobar Islands', 'rajendranpalaniappan@rediffmail.com');
INSERT INTO user VALUES ('269', 'ANDAMAN LEISURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('270', 'KITE INFRATECH PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'prasanna1970@gmail.com');
INSERT INTO user VALUES ('271', 'DEEP SEA RESORT (ANDAMAN) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('272', 'HOLIDAY 2 ANDAMAN CORPORATE AND LEISURE TRAVELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'holiday2andaman@gmail.com');
INSERT INTO user VALUES ('273', 'ANDAMAN & NICOBAR MINERAL WATER PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'RAJENDRAN.ANI24@GMAIL.COM');
INSERT INTO user VALUES ('274', 'ANDAMAN SEA WONDERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'SMJAVEDJAFRIN@GMAIL.COM');
INSERT INTO user VALUES ('275', 'SAFECRACKERS TRAVEL AND EXCURSIONS INDIA (OPC) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'KARTEEK.TARUN@GMAIL.COM');
INSERT INTO user VALUES ('276', 'ENCHANTING ANDAMANS TOUR (OPC) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'reachandamans@gmail.com');
INSERT INTO user VALUES ('277', 'VERTIGO INFRASTRUCTURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'SURAJSELVAM25@GMAIL.COM');
INSERT INTO user VALUES ('278', 'NABAJIT REAL ESTATE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'INDRAJITMISTRY68@GMAIL.COM');
INSERT INTO user VALUES ('279', 'MYUZ HOSPITALITY SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ripos@andamanexoticholidays.com');
INSERT INTO user VALUES ('280', 'SCUBA ADVENTURES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'santosh.dayarkar@gmail.com');
INSERT INTO user VALUES ('281', 'BAUL & SONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'baulindia57@gmail.com');
INSERT INTO user VALUES ('282', 'ANDAMAN AIRWAYS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'nadeemixz@gmail.com');
INSERT INTO user VALUES ('283', 'ANDAMAN AQUA WATER SPORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'SUNILMUKUL_89@REDIFFMAIL.COM');
INSERT INTO user VALUES ('284', 'RUBIECUBE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'rubiecubepvtltd@gmail.com');
INSERT INTO user VALUES ('285', 'COLOURS OF EMERALD ISLANDS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ramesh@divemantra.com');
INSERT INTO user VALUES ('286', 'SHADELOFT INNOVATION PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mac.seagem@gmail.com');
INSERT INTO user VALUES ('287', 'MEMORIES ANDAMAN TRAVELS AND ADVENTURES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sunilmukul_sa@rediffmail.com');
INSERT INTO user VALUES ('288', 'DUGONG SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'manishraj280389@gmail.com');
INSERT INTO user VALUES ('289', 'ANDAMAN SEA TREK ADVENTURES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'kd.anup@gmail.com');
INSERT INTO user VALUES ('290', 'ANDAMAN GALAXY SHIP MANAGEMENT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'nvsabith@gmail.com');
INSERT INTO user VALUES ('291', 'ANDAMAN REEF PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'shiprabikram@yahoo.com');
INSERT INTO user VALUES ('292', 'RITIKA'S DIAGNOSTIC SOLUTIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'solutionsdiagnostic@gmail.com');
INSERT INTO user VALUES ('293', 'OFF ROAD SPORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'contact@andamanisland.in');
INSERT INTO user VALUES ('294', 'ANDAMAN SAHA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'kawshiksaha26@gmail.com');
INSERT INTO user VALUES ('295', 'YELLOWBOARD VACATIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ashwin_d@live.com');
INSERT INTO user VALUES ('296', '100KEYS TRADECOM PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'contact@tttrading.in');
INSERT INTO user VALUES ('297', 'REEF VALLEY RESORT (OPC) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'dr.bhagirathdebnath@gmail.com');
INSERT INTO user VALUES ('298', 'ADORABLE ANDAMAN LEISURE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sunilmukul1004@gmail.com');
INSERT INTO user VALUES ('299', 'ISLAND DATA SOLUTIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sunshinecables@gmail.com');
INSERT INTO user VALUES ('300', 'SHRINE MEDIA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'annu.ixz@gmail.com');
INSERT INTO user VALUES ('301', 'EKOISLAND HOSPITALITY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'khadi999@gmail.com');
INSERT INTO user VALUES ('302', 'MEENAKSHI SHIPPING SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'meenakshishipping@gmail.com');
INSERT INTO user VALUES ('303', 'SEVENHILLS GOLD & SILVER PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'trmurugeshan@gmail.com');
INSERT INTO user VALUES ('312', 'INLAND MARINE WORKS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('313', 'RAJ MARINE SERVICES PRIVATE LIMITED.', 'Andaman and Nicobar Islands', 'rajcocal@yahoo.co.in');
INSERT INTO user VALUES ('316', 'MAK LOGISTICS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'makpbl@yahoo.com');
INSERT INTO user VALUES ('317', 'I T T LINES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'add_associates@yahoo.in');
INSERT INTO user VALUES ('318', 'RAHMAT SHIPPING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('319', 'STAR SHIPPING LOGISTICS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ravichandransca@yahoo.com');
INSERT INTO user VALUES ('320', 'GREEN OCEAN SEAWAYS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sunilsreedharan@gmail.com');
INSERT INTO user VALUES ('321', 'SEA CABS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'NVSABITH@GMAIL.COM');
INSERT INTO user VALUES ('322', 'SAKTHI SHIPPING SERVICES (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('323', 'DOONGI DIVES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@vlp.co.in');
INSERT INTO user VALUES ('324', 'DIVE ANDAMAN (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('325', 'FULI AQUA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('326', 'PRASANTA SHIPPING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'NIKHILKUMARDHALI75@GMAIL.COM');
INSERT INTO user VALUES ('327', 'NACHI MARINE SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'kavitaravi75@outlook.com');
INSERT INTO user VALUES ('328', 'PROMILA SHIPPING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'HARILAL8485@GMAIL.COM');
INSERT INTO user VALUES ('329', 'KUCHAT SHIPPING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'hsamuelkuchat@gmail.com');
INSERT INTO user VALUES ('330', 'ABLE AVIATION (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'nadeem@able-aviation.com');
INSERT INTO user VALUES ('331', 'BIZ AVIATIONS AND LOGISTIC PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mahabirtradingpb@yahoo.com');
INSERT INTO user VALUES ('332', 'SEA LINK AQUA VENTURES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'asif_spacelink@yahoo.com');
INSERT INTO user VALUES ('333', 'ANDAMAN GAME FISHING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('334', 'APT LOGISTICS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('335', 'ONLINE ANDAMAN TRAVEL PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('336', 'ANDABAR COLD STORES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'vaksusi@gmail.com');
INSERT INTO user VALUES ('337', 'SAGAR KUMARI SHIPPING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'vikaslalp@gmail.com');
INSERT INTO user VALUES ('338', 'MAKE MY JOURNEY (OPC) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'IHAROY@GMAIL.COM');
INSERT INTO user VALUES ('339', 'ANDAMAN EXCURSION PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('340', 'CUSP TRAVEL SOLUTIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roseminegroup@gmail.com');
INSERT INTO user VALUES ('341', 'ANDAMAN BLUE QUEEN TRAVEL SOLUTIONS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'gsureshdebe@gmail.com');
INSERT INTO user VALUES ('342', 'GURUGRAM SIRSA TRANSPORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'bizpackers2011@gmail.com');
INSERT INTO user VALUES ('343', 'YOUR DREAM JOURNEY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'djsajid22@gmal.com');
INSERT INTO user VALUES ('344', 'BAY ISLAND TRADING AND MARINE SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'cababubadat@gmail.com');
INSERT INTO user VALUES ('348', 'ISLAND TRAVELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'islandtravels@yahoo.com');
INSERT INTO user VALUES ('350', 'ANDAMAN EXPLORERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babubadat@gmail.com');
INSERT INTO user VALUES ('351', 'ANDAMAN HOLIDAYS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'dscchennai@yahoo.in');
INSERT INTO user VALUES ('352', 'FC TOURS AND RESORTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ssaandco@yahoo.com');
INSERT INTO user VALUES ('353', 'ANDAMAN WORLD TRAVELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'andamanworldtravels@gmail.com');
INSERT INTO user VALUES ('354', 'R D R TRAVEL ADVISORS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('355', 'GLOBUS AVIATION PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('356', 'HEAVEN ON OCEAN TOURISM PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'gauthamjai06@yahoo.co.in');
INSERT INTO user VALUES ('357', 'SANDS OF ANDAMAN TRAVEL PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'resrvation@sandsofandaman.com');
INSERT INTO user VALUES ('358', 'WEBPORT MEDIA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'legal@webport.in');
INSERT INTO user VALUES ('359', 'WELCOME ANDAMAN TRAVELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'CONTACT@WELCOMEANDAMANISLANDS.COM');
INSERT INTO user VALUES ('360', 'BLUECRAFT HOLIDAYS LEISURE (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'BLUECRAFTHOLIDAYS@GMAIL.COM');
INSERT INTO user VALUES ('361', 'WOODLAND TRAVELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('362', 'ANDAMAN VISION TOUR & TRAVELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'tanumaguha@gmail.com');
INSERT INTO user VALUES ('363', 'EXPERIENCE ANDAMANS TOURS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'azhar@experienceandamans.com');
INSERT INTO user VALUES ('364', 'BOND OCEAN SAFARI ANDAMAN PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'sandigit@gmail.com');
INSERT INTO user VALUES ('365', 'CLUB TAXI AND TRAVELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ashah021211@gmail.com');
INSERT INTO user VALUES ('366', 'GREEN ISLANDS INSTITUTE OF COMPUTER TRAINING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'tapasroy7@gmail.com');
INSERT INTO user VALUES ('367', 'TECH EDUCATION2 PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc.casatya@gmail.com');
INSERT INTO user VALUES ('368', 'VIDYA YUVAKENDRA FOUNDATION', 'Andaman and Nicobar Islands', 'subbiahandco@gmail.com');
INSERT INTO user VALUES ('369', 'ROHIN'S HOSPITAL PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'rohindra_lall@yahoo.com');
INSERT INTO user VALUES ('370', 'WELLCARE AYURVEDALAYAM (ANDAMAN) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'andamanhealth@gmail.com');
INSERT INTO user VALUES ('371', 'MALLICK CONSULTANCY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mallickconsultancy@gmail.com');
INSERT INTO user VALUES ('373', 'YOGI FINANCE AND INVESTMENTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mehtakolkata@vsnl.net');
INSERT INTO user VALUES ('374', 'ISLANDERS MARGIN FREE FINSERVICE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'kesavan@icai.org');
INSERT INTO user VALUES ('375', 'MAINAK PROJECTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mainak_pbl_andamans@yahoo.co.in');
INSERT INTO user VALUES ('376', 'ANDAMAN BUBBLES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mhjadwet@hotmail.com');
INSERT INTO user VALUES ('377', 'MANTRA WATER SPORTS EQUIPMENT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'roc@vlp.co.in');
INSERT INTO user VALUES ('378', 'ECO DIVER INDIA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'info@ecodiver.in');
INSERT INTO user VALUES ('379', 'A&N CRICKET FEDERATION', 'Andaman and Nicobar Islands', 'jainkgupta@gmail.com');
INSERT INTO user VALUES ('380', 'DEGREE CELSIUS TOURISM PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'cam.rat10@gmail.com');
INSERT INTO user VALUES ('383', 'HIGH SEAS SPORTS CLUB PRIVATE LIMITED (OPC)', 'Andaman and Nicobar Islands', 'DRYMBEI@GMAIL.COM');
INSERT INTO user VALUES ('384', 'STARFISH ADVENTURES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'tauseefrasheed21@gmail.com');
INSERT INTO user VALUES ('385', 'KP GAMES AND EATERIES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'babu.badat@gmail.com');
INSERT INTO user VALUES ('386', 'DIVEINDIA EXPLORER PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'vnairi09@gmail.com');
INSERT INTO user VALUES ('387', 'ANDAMAN ISLAND TRAVELS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'CONTACT@ANDAMANISLAND.IN');
INSERT INTO user VALUES ('388', 'ANDAMAN ESCAPADES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('389', 'BIZ PACKERS AND MOVERS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'BIZPACKERS2011@GMAIL.COM');
INSERT INTO user VALUES ('390', 'KUBER DHANMANTHAN MULTI LEVEL MARKETING(INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'efiling.chanakya@gmail.com');
INSERT INTO user VALUES ('391', 'INCREDIBLE ANDAMAN TOURISM (INDIA) PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.COM.IN');
INSERT INTO user VALUES ('392', 'PGK EDUCATIONAL SERVICES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'pragatiandaman@gmail.com');
INSERT INTO user VALUES ('393', 'PATROL MOBILE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'CA.PATEL@VLP.CO.IN');
INSERT INTO user VALUES ('394', 'HAVELOCK ISLAND BEACH RESORT PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'CONTACT@ANADAMANISLAND.IN');
INSERT INTO user VALUES ('395', 'ANDAMAN ECSTASY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'esctasyandaman@gmail.com');
INSERT INTO user VALUES ('396', 'ANDAMAN SEA KING PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'mallickconsultancy@gmail.com');
INSERT INTO user VALUES ('397', 'ORCHESTRATE HOLIDAY PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('398', 'ANDAMAN SCRIBES PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ONJAISWAL@GMAIL.COM');
INSERT INTO user VALUES ('399', 'NANDANAM COMMUNICATION & AUTOTRADE PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'RAHULN033@GMAIL.COM');
INSERT INTO user VALUES ('400', 'ANDAMAN XTASEA EVENTS PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ecstasyeventspvt.ltd@gmail.com');
INSERT INTO user VALUES ('401', 'DIVE MANTRA PRIVATE LIMITED', 'Andaman and Nicobar Islands', 'ROC@VLP.CO.IN');
INSERT INTO user VALUES ('402', 'PORT BLAIR SMART PROJECTS LIMITED', 'Andaman and Nicobar Islands', 'smartcityportblair@gmail.com');
